version: '2'
services:
  master:
    image: alfalfalfa/mysql-master
    environment:
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - "3306"
    ports:
      - "33306:3306"
  slave:
    image: alfalfalfa/mysql-slave
    depends_on:
      - master
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_MASTER_SERVER=master
      - MYSQL_MASTER_ROOT_PASS=root
      - MYSQL_MASTER_WAIT_TIME=5
    links:
      - master
    expose:
      - "3306"
    ports:
      - "33307:3306"
